<?php

namespace shop\ui;

class UIProjectExampleButton extends UIActionButton
{
    protected $classContainer = "example-action-button";

    public function setState($value)
    {
        // TODO: Change the autogenerated stub
    }

}